# Generated by Django 5.2.6 on 2025-09-07 16:04

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProAuthorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_legal', models.CharField(max_length=120)),
                ('last_name_legal', models.CharField(max_length=120)),
                ('national_id', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Thailand', max_length=80)),
                ('id_card_image', models.ImageField(upload_to=accounts.models.pro_doc_upload_path)),
                ('selfie_image', models.ImageField(upload_to=accounts.models.pro_doc_upload_path)),
                ('extra_doc', models.FileField(blank=True, null=True, upload_to=accounts.models.pro_doc_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pro_apps', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pro Author Application',
                'verbose_name_plural': 'Pro Author Applications',
            },
        ),
    ]
